name: pull request workflow

on:
  pull_request:
    branches:
      - main
      
jobs:
  builds:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Grant Permissions to gradlew
      run: chmod +x gradlew
    - name: Run Application Tests
      run: ./gradlew clean test
