name: pull request merge workflow

on:
  pull_request:
#    types: [closed]
    branches:
      - main

jobs:
  builds:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Build Image Gradle
        run: ./gradlew bootBuildImage