name: pull request workflow

on:
  pull_request:
    branches:
      - main
      
jobs:
  builds:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - run: java HelloWorldApp.java
